Controllers/DetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DOANWEBDULICH.Models;

namespace DOANWEBDULICH.Controllers
{
    public class DetailsController : Controller
    {
        dbQLDuLichDataContext data = new dbQLDuLichDataContext();
        // GET: Details

        public ActionResult DetailsDL(string id)
        {
            var tour = from t in data.TOURDULICHes
                       where t.IDTOUR == id
                       select t;
            return View(tour);
        }
        public ActionResult DetailsKS(string id)
        {
            var khachsan = from t in data.KHACHSANs
                       where t.IDKS == id
                       select t;
            return View(khachsan);
        }
        public ActionResult DetailsXe(string id)
        {
            var Xe = from t in data.PHUONGTIENs
                           where t.IDPT == id
                           select t;
            return View(Xe);
        }
    }
}

Controllers/DichVuController.cs
using DOANWEBDULICH.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DOANWEBDULICH.Controllers
{
    public class DichVuController : Controller
    {
        dbQLDuLichDataContext data = new dbQLDuLichDataContext();
        // GET: DichVu
        public ActionResult ThueXe()
        {
            

            var xedl = (from s in data.PHUONGTIENs select s).ToList();

            return View(xedl);

        }

        public ActionResult KhachSan()
        {
            var ks = (from k in data.KHACHSANs select k).ToList();

            return View(ks);
        }
    }
}

Views/DichVu/KhachSan.cshtml
@{
    ViewBag.Title = "KhachSan";
    Layout = "~/Views/Layout/Nav.cshtml";
}
@model IEnumerable<DOANWEBDULICH.Models.KHACHSAN>


<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
    <title>KhachSan</title>
    <link rel="shortcut icon" type="image/icon" href="~/Logo/favicon.png" />
    <link rel="stylesheet" href="~/CSS/font-awesome.min.css" />
    <link rel="stylesheet" href="~/CSS/animate.css" />
    <link rel="stylesheet" href="~/CSS/hover-min.css">
    <link rel="stylesheet" href="~/CSS/datepicker.css">
    <link rel="stylesheet" href="~/CSS/owl.carousel.min.css">
    <link rel="stylesheet" href="~/CSS/owl.theme.default.min.css" />
    <link rel="stylesheet" href="~/CSS/jquery-ui.min.css" />
    <link rel="stylesheet" href="~/CSS/bootstrap.min.css" />
    <link rel="stylesheet" href="~/CSS/bootsnav.css" />
    <link rel="stylesheet" href="~/CSS/style.css" />
    <link rel="stylesheet" href="~/CSS/responsive.css" />
    <link href="~/CSS/margin.css" rel="stylesheet" />

</head>
<body  style="background-color: #cecece12">

    <!--travel-box end-->
    <section id="pack" class="packages">
        <div class="container">
            <div class="gallary-header text-center">
                <h2>
                    special packages
                </h2>
            </div><!--/.gallery-header-->
            @foreach (var kHACHSAN in Model)
            {
                <div class="packages-content">
                    <div>
                        <div class="col-md-4 col-sm-6">
                            <div style="background-color: white" class="single-package-item">
                                <img src="~/PIC/PicHome/KsPic/@kHACHSAN.ANH" alt="package-place">
                                <div class="single-package-item-txt">
                                    <h3> @kHACHSAN.TENKS <span class="pull-right">@kHACHSAN.GIA VND</span></h3> <!--/Ten Du Lich-->
                                    <div class="packages-para">
                                        <p>
                                            <span>
                                                <i class="fa fa-angle-right"></i> @kHACHSAN.TINHTRANG Phòng  <!--Số Ngày-->
                                            </span>
                                        </p>
                                    </div><!--/.packages-para-->
                                    <div class="packages-review">
                                        <p>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                        </p>
                                    </div><!--/.packages-review-->
                                    <div class="about-btn">
                                        <button class="about-view packages-btn">
                                            <a href="@Url.Action("DetailsKS", "Details", new { id = kHACHSAN.IDKS })">book now</a>
                                        </button>
                                    </div><!--/.about-btn-->
                                </div><!--/.single-package-item-txt-->
                            </div><!--/.single-package-item-->
                        </div><!--/.col-->
                    </div><!--/.row-->
                </div><!--/.packages-content-->
            }
        </div><!--/.container-->
    </section><!--/.packages-->
    <!--packages end-->

</body>
</html>

Views/DichVu/ThueXe.cshtml
@model IEnumerable<DOANWEBDULICH.Models.PHUONGTIEN>

@{
    ViewBag.Title = "ThueXe";
    Layout = "~/Views/Layout/Nav.cshtml";
}


<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
    <title>Travel</title>
    <link rel="shortcut icon" type="image/icon" href="~/Logo/favicon.png" />
    <link rel="stylesheet" href="~/CSS/font-awesome.min.css" />
    <link rel="stylesheet" href="~/CSS/animate.css" />
    <link rel="stylesheet" href="~/CSS/hover-min.css">
    <link rel="stylesheet" href="~/CSS/datepicker.css">
    <link rel="stylesheet" href="~/CSS/owl.carousel.min.css">
    <link rel="stylesheet" href="~/CSS/owl.theme.default.min.css" />
    <link rel="stylesheet" href="~/CSS/jquery-ui.min.css" />
    <link rel="stylesheet" href="~/CSS/bootstrap.min.css" />
    <link rel="stylesheet" href="~/CSS/bootsnav.css" />
    <link rel="stylesheet" href="~/CSS/style.css" />
    <link rel="stylesheet" href="~/CSS/responsive.css" />
    <link href="~/CSS/margin.css" rel="stylesheet" />

</head>
<body style="background-color: #cecece12">


    <section id="pack" class="packages">
        <div class="container">
            <div style="color: black" class="gallary-header text-center">
                <h2>
                    Xe Du Lịch
                </h2>
            </div><!--/.gallery-header-->
            @foreach (var PHUONGTIEN in Model)
            {
                <div class="packages-content">
                    <div>
                        <div class="col-md-4 col-sm-6">
                            <div style="background-color: white" class="single-package-item">
                                <img src="~/PIC/PicHome/XePic/@PHUONGTIEN.ANH" alt="package-place">
                                <div class="single-package-item-txt">
                                    <h3> @PHUONGTIEN.TENPT </h3> <!--/Ten Du Lich-->
                                    <div class="packages-para">
                                        <p>
                                            <span>
                                                <i class="fa fa-angle-right"></i> @PHUONGTIEN.LOAIPT  <!--Số Ngày-->
                                            </span>
                                        </p>
                                    </div><!--/.packages-para-->
                                    <div class="packages-review">
                                        <p>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                        </p>
                                    </div><!--/.packages-review-->
                                    <div class="about-btn">
                                        <button class="about-view packages-btn">
                                            <a href="@Url.Action("DetailsXe", "Details", new { id = PHUONGTIEN.IDPT })">book now</a>
                                        </button>
                                    </div><!--/.about-btn-->
                                </div><!--/.single-package-item-txt-->
                            </div><!--/.single-package-item-->
                        </div><!--/.col-->
                    </div><!--/.row-->
                </div><!--/.packages-content-->
            }
        </div><!--/.container-->
    </section><!--/.packages-->
    <!--packages end-->

</body>
</html>