Controllers/DichVuController.cs
using DOANWEBDULICH.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DOANWEBDULICH.Controllers
{
    public class DichVuController : Controller
    {
        dbQLDuLichDataContext data = new dbQLDuLichDataContext();
        // GET: DichVu
        public ActionResult ThueXe()
        {
            

            var xedl = (from s in data.PHUONGTIENs select s).ToList();

            return View(xedl);

        }

        public ActionResult KhachSan()
        {
            var ks = (from k in data.KHACHSANs select k).ToList();

            return View(ks);
        }
    }
}

Controllers/DuLichController.cs
using DOANWEBDULICH.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace DOANWEBDULICH.Controllers
{
    public class DuLichController : Controller
    {
        dbQLDuLichDataContext data = new dbQLDuLichDataContext();
        // GET: DuLich

        private List<MIEN> mbac(int count)
        {
            return data.MIENs.OrderByDescending(a => a.IDMIEN).Take(count).ToList();
        }

        public ActionResult DuLichMB ()
        {
            var MB = (from s in data.TOURDULICHes
                            where s.MIEN.IDMIEN == "MIB"
                            select s).ToList();

            return View(MB);
        }

        public ActionResult DuLichMT()
        {
            var MT = (from s in data.TOURDULICHes
                      where s.MIEN.IDMIEN == "MIT"
                      select s).ToList();
            return View(MT);
        }

        public ActionResult DuLichMN()
        {
            var MN = (from s in data.TOURDULICHes
                      where s.MIEN.IDMIEN == "MIN"
                      select s).ToList();
            return View(MN);
        }




    }
}

Views/Layout/Nav.cshtml
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
    <!-- META DATA -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <!--font-family-->
    <link href="https://fonts.googleapis.com/css?family=Rufina:400,700" rel="stylesheet" />

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
    <title>Travel</title>
    <link rel="shortcut icon" type="image/icon" href="~/Logo/favicon.png" />
    <link rel="stylesheet" href="~/CSS/font-awesome.min.css" />
    <link rel="stylesheet" href="~/CSS/animate.css" />
    <link rel="stylesheet" href="~/CSS/hover-min.css">
    <link rel="stylesheet" href="~/CSS/datepicker.css">
    <link rel="stylesheet" href="~/CSS/owl.carousel.min.css">
    <link rel="stylesheet" href="~/CSS/owl.theme.default.min.css" />
    <link rel="stylesheet" href="~/CSS/jquery-ui.min.css" />
    <link rel="stylesheet" href="~/CSS/bootstrap.min.css" />
    <link rel="stylesheet" href="~/CSS/bootsnav.css" />
    <link rel="stylesheet" href="~/CSS/style.css" />
    <link rel="stylesheet" href="~/CSS/responsive.css" />

    <style>
        #font a {
            color: white;
            transition: 0.6s;
        }

            #font a:hover {
                color: orange;
                transition: 0.6s;
            }

        #logo a {
            color: aqua;
            transition: 0.6s;
        }

            #logo a span:hover {
                color: aqua;
                transition: 0.6s;
            }

            #logo a:hover {
                color: orange;
                transition: 0.6s;
            }
    </style>
</head>
<body>
    <header class="top-area">
        <div style="background-color: black" class="header-area">
            <div class="container">
                <div class="row">
                    <div class="col-sm-2">
                        <div id="logo" class="logo">
                            <a href="@Url.Action("TrangChu", "Home")">
                                Tour<span>LH</span>
                            </a>
                        </div><!-- /.logo-->
                    </div><!-- /.col-->
                    <div class="col-sm-10">
                        <div class="main-menu">

                            <!-- Brand and toggle get grouped for better mobile display -->
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                    <i class="fa fa-bars"></i>
                                </button><!-- / button-->
                            </div><!-- /.navbar-header-->
                            <div class="collapse navbar-collapse">
                                <ul class="nav navbar-nav navbar-right">
                                    <li id="font" class="smooth-menu"><a href="@Url.Action("TrangChu", "Home")"><b>Trang Chủ</b></a></li>
                                    <li id="font" class="smooth-menu"><a href="@Url.Action("DuLichMB", "DuLich")"><b>Miền Bắc</b></a></li>
                                    <li id="font" class="smooth-menu"><a href="@Url.Action("DuLichMT", "DuLich")"><b>Miền Trung</b> </a></li>
                                    <li id="font" class="smooth-menu"><a href="@Url.Action("DuLichMN", "DuLich")"><b>Miền Nam</b></a></li>
                                    <li id="font" class="smooth-menu"><a href="@Url.Action("KhachSan", "DichVu")"><b>Khách Sạn</b></a></li>
                                    <li id="font" class="smooth-menu"><a href="@Url.Action("ThueXe", "DichVu")"><b>Đặt Xe</b></a></li>
                                    <li id="font" class="smooth-menu"><a href="@Url.Action("DangNhap", "Home")"><b> Đăng Nhập</b></a></li>

                                </ul>
                            </div><!-- /.navbar-collapse -->
                        </div><!-- /.main-menu-->
                    </div><!-- /.col-->
                </div><!-- /.row -->
                <div class="home-border"></div><!-- /.home-border-->
            </div><!-- /.container-->
        </div><!-- /.header-area -->

    </header><!-- /.top-area-->
    <!-- main-menu End -->

    <div>

        @RenderBody()
    </div>
</body>
</html>

Views/Layout/_LayoutAdmin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="~/CSS/CssAdmin2/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/CSS/CssAdmin2/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="~/CSS/CssAdmin2/dist/css/skins/_all-skins.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/CSS/CssAdmin2/plugins/iCheck/flat/blue.css">
    <!-- Morris chart -->
    <link rel="stylesheet" href="~/CSS/CssAdmin2/plugins/morris/morris.css">
    <!-- jvectormap -->
    <link rel="stylesheet" href="~/CSS/CssAdmin2/plugins/jvectormap/jquery-jvectormap-1.2.2.css">
    <!-- Date Picker -->
    <link rel="stylesheet" href="~/CSS/CssAdmin2/plugins/datepicker/datepicker3.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/CSS/CssAdmin2/plugins/daterangepicker/daterangepicker-bs3.css">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="~/CSS/CssAdmin2/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="~/tinymce/js/tinymce/tinymce.min.js"></script>
    <script>tinymce.init({ selector: 'textarea' });</script>
</head>
<body  class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">

        <header class="main-header">
            <!-- Logo -->
            <a href="/QuanTri/Index" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>L</b>H</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>TOUR</b>LH</span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <!-- sidebar: style can be found in sidebar.less -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <div class="user-panel">
                    <div class="pull-left info">
                        <p>HELLO ADMIN</p>
                        <a href="#"><i class="fa fa-circle text-success"></i>ĐANG RÃNH LẮM</a>
                    </div>
                </div>
                <!-- search form -->
                <!-- /.search form -->
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu">
                    <li class="header">THANH ĐIỀU KHIỂN</li>
                    <li class="active treeview">
                        <a href="#">
                            <i class="fa fa-dashboard"></i> <span>QUẢN LÝ ITEM</span> <i class="fa fa-angle-left pull-right"></i>
                        </a>
                        <ul class="treeview-menu">
                            <li ><i class="fa fa-circle-o"></i>@Html.ActionLink("TOUR DU LỊCH", "DuLich", "QuanTri")</li>
                            <li ><i class="fa fa-circle-o"></i> @Html.ActionLink("QUẢN LÝ XE", "ThueXe", "QuanTri") </li>
                            <li ><i class="fa fa-circle-o"></i> @Html.ActionLink("KHÁCH SẠN", "KhachSan", "QuanTri") </li>
                        </ul>
                    </li>
                    <li class="active treeview">
                        <a href="#">
                            <i class="fa fa-dashboard"></i> <span>QUẢN LÝ VÉ</span> <i class="fa fa-angle-left pull-right"></i>
                        </a>
                        <ul class="treeview-menu">
                            <li ><i class="fa fa-circle-o"></i>@Html.ActionLink("VÉ TOUR", "VeTour", "QuanTri")</li>
                            <li><i class="fa fa-circle-o"></i> @Html.ActionLink("ĐƠN ĐẶT PHÒNG", "DonDatPhong", "QuanTri") </li>
                            <li><i class="fa fa-circle-o"></i> @Html.ActionLink("VÉ XE", "VeXe", "QuanTri") </li>
                        </ul>
                    </li>
                </ul>
            </section>
            <!-- /.sidebar -->
    </div><!-- ./wrapper -->
    <!-- jQuery 2.1.4 -->
    <script src="~/CSS/CssAdmin2/plugins/jQuery/jQuery-2.1.4.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
      $.widget.bridge('uibutton', $.ui.button);
    </script>
    <!-- Bootstrap 3.3.5 -->
    <script src="~/CSS/CssAdmin2/bootstrap/js/bootstrap.min.js"></script>
    <!-- Morris.js charts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="~/CSS/CssAdmin2/plugins/morris/morris.min.js"></script>
    <!-- Sparkline -->
    <script src="~/CSS/CssAdmin2/plugins/sparkline/jquery.sparkline.min.js"></script>
    <!-- jvectormap -->
    <script src="~/CSS/CssAdmin2/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="~/CSS/CssAdmin2/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="~/CSS/CssAdmin2/plugins/knob/jquery.knob.js"></script>
    <!-- daterangepicker -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js"></script>
    <script src="~/CSS/CssAdmin2/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- datepicker -->
    <script src="~/CSS/CssAdmin2/plugins/datepicker/bootstrap-datepicker.js"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <script src="plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
    <!-- Slimscroll -->
    <script src="~/CSS/CssAdmin2/plugins/slimScroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="plugins/fastclick/fastclick.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/CSS/CssAdmin2/dist/js/app.min.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/CSS/CssAdmin2/dist/js/pages/dashboard.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/CSS/CssAdmin2/dist/js/demo.js"></script>


    <div class="content-wrapper">

        @RenderBody()

    </div>

</body>
</html>